# Use an official Tomcat image as the base
FROM tomcat:9-jdk17

# Remove the default web applications
RUN rm -rf /usr/local/tomcat/webapps

# Copy your WAR file to the Tomcat webapps directory
COPY target/frontend-0.0.1-SNAPSHOT.war  /usr/local/tomcat/webapps/ROOT.war

# Expose port 8080 (default port for Tomcat)
EXPOSE 8080
