# Use an openjdk base image for your container
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from your local machine to the container
COPY target/backend-0.0.1-SNAPSHOT.jar /app/backend.jar

# Expose the port the app will run on
EXPOSE 8081

# Command to run the application
ENTRYPOINT ["java", "-jar", "backend.jar"]
